name: 'GitHub Actions Luogu Auto Sign In'

on:
  watch:
    types: started
  push:
  schedule:
    - cron: '0 5 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v1
        - name: 'Set up Python'
          uses: actions/setup-python@v1
          with:
            python-version: '3.7'
        - name: 'Install requirements'
          run: |
            python -m pip install --upgrade pip
            pip install requests
        - name: 'AutoClick'
          run: python main.py
